apiVersion: v1
kind: Service
metadata:
  name: minecraft-server
  namespace: minecraft
  labels:
    app: minecraft-server
spec:
  type: NodePort
  ports:
    - port: {{ .Values.minecraft.port }}
      nodePort: {{ .Values.minecraft.port }}
  selector:
    app: minecraft-server
