apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-minecraft-pvc
  namespace: minecraft
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 10Gi
